import { beforeEach, describe, expect, test, vi } from "vitest"

const { mockExecute, mockFindFirst } = vi.hoisted(() => ({
  mockExecute: vi.fn(),
  mockFindFirst: vi.fn(),
}))

const mockSql = Object.assign(
  (strings: TemplateStringsArray, ...values: unknown[]) => ({
    strings: [...strings],
    values,
  }),
  { join: vi.fn((chunks: unknown[]) => ({ chunks })) },
)

vi.mock("@chatbotx.io/database/client", () => ({
  db: {
    execute: mockExecute,
    query: { contactInboxModel: { findFirst: mockFindFirst } },
  },
  sql: mockSql,
}))

const {
  currentFlowStepService,
  isAutoGeneratedNodeName,
  pickLatestCurrentFlowNode,
  resolveFlowNodeDisplay,
  truncatePreview,
} = await import("../src/flow/current-step")

const sendMessageNode = (name: string, steps: unknown[] = []) => ({
  id: "node-1",
  type: "sendMessage",
  data: { name, isStartNode: false, details: { steps, quickReplies: [] } },
})

describe("resolveFlowNodeDisplay", () => {
  test("uses the name the user gave the node, without a preview", () => {
    expect(
      resolveFlowNodeDisplay(
        sendMessageNode("Ask for phone", [
          { stepType: "sendText", text: "Please send your phone number" },
        ]),
      ),
    ).toEqual({
      nodeType: "sendMessage",
      nodeName: "Ask for phone",
      nodePreview: null,
    })
  })

  test("adds the first words of the text to an auto-generated name", () => {
    expect(
      resolveFlowNodeDisplay(
        sendMessageNode("Отправить сообщение #3", [
          { stepType: "typing" },
          {
            stepType: "sendText",
            text: "Здравствуйте! Чем мы можем вам помочь сегодня вечером?",
          },
        ]),
      ),
    ).toEqual({
      nodeType: "sendMessage",
      nodeName: "Отправить сообщение #3",
      nodePreview: "Здравствуйте! Чем мы можем вам помочь…",
    })
  })

  test("strips rich-text markup from v2 text", () => {
    const display = resolveFlowNodeDisplay(
      sendMessageNode("Send Message", [
        { stepType: "sendText", version: "v2", text: "<b>Hello</b> there" },
      ]),
    )
    expect(display.nodePreview).toBe("Hello there")
  })

  test("falls back to a getUserData question", () => {
    const display = resolveFlowNodeDisplay(
      sendMessageNode("Send Message #1", [
        { stepType: "getUserData", message: "What is your email?" },
      ]),
    )
    expect(display.nodePreview).toBe("What is your email?")
  })

  test("returns no name for a blank name and keeps the type", () => {
    expect(
      resolveFlowNodeDisplay({
        id: "n",
        type: "condition",
        data: { name: "   " },
      }),
    ).toEqual({ nodeType: "condition", nodeName: null, nodePreview: null })
  })

  test("never throws on missing or malformed nodes", () => {
    const empty = { nodeType: null, nodeName: null, nodePreview: null }
    expect(resolveFlowNodeDisplay(undefined)).toEqual(empty)
    expect(resolveFlowNodeDisplay("node")).toEqual(empty)
    expect(resolveFlowNodeDisplay({ type: "unknownType", data: 1 })).toEqual(
      empty,
    )
  })
})

describe("helpers", () => {
  test("isAutoGeneratedNodeName", () => {
    expect(isAutoGeneratedNodeName("Send Message #12")).toBe(true)
    expect(isAutoGeneratedNodeName("Wait")).toBe(true)
    expect(isAutoGeneratedNodeName("Qualify lead")).toBe(false)
    expect(isAutoGeneratedNodeName("Step #2 follow-up")).toBe(false)
  })

  test("truncatePreview", () => {
    expect(truncatePreview("  one\n two  ")).toBe("one two")
    expect(truncatePreview("   ")).toBeNull()
    expect(truncatePreview("a".repeat(80))).toBe(`${"a".repeat(60)}…`)
  })

  test("pickLatestCurrentFlowNode picks the most recent complete row", () => {
    const rows = [
      {
        id: "1",
        currentFlowId: "f",
        currentNodeId: "a",
        currentNodeAt: new Date("2026-10-01T00:00:00Z"),
      },
      {
        id: "2",
        currentFlowId: "f",
        currentNodeId: "b",
        currentNodeAt: new Date("2026-10-03T00:00:00Z"),
      },
      {
        id: "3",
        currentFlowId: null,
        currentNodeId: null,
        currentNodeAt: null,
      },
    ]
    expect(pickLatestCurrentFlowNode(rows)?.id).toBe("2")
    expect(pickLatestCurrentFlowNode([rows[2]])).toBeNull()
    expect(pickLatestCurrentFlowNode(undefined)).toBeNull()
  })
})

describe("currentFlowStepService.resolveMany", () => {
  const reachedAt = new Date("2026-10-05T10:00:00Z")

  beforeEach(() => {
    vi.clearAllMocks()
  })

  test("does not query when no ref is recorded", async () => {
    const result = await currentFlowStepService.resolveMany({
      workspaceId: "ws",
      refs: [
        null,
        { currentFlowId: null, currentNodeId: null, currentNodeAt: null },
      ],
    })
    expect(result).toEqual([null, null])
    expect(mockExecute).not.toHaveBeenCalled()
  })

  test("resolves a page of refs with a single query", async () => {
    mockExecute.mockResolvedValue({
      rows: [
        {
          flowId: 10,
          flowName: "Onboarding",
          nodeId: "node-1",
          node: sendMessageNode("Ask for phone"),
        },
        // Flow exists but its published version no longer has node-x.
        { flowId: "20", flowName: "Sales", nodeId: null, node: null },
      ],
    })

    const result = await currentFlowStepService.resolveMany({
      workspaceId: "ws",
      refs: [
        {
          currentFlowId: "10",
          currentNodeId: "node-1",
          currentNodeAt: reachedAt,
        },
        null,
        {
          currentFlowId: "20",
          currentNodeId: "node-x",
          currentNodeAt: reachedAt,
        },
        // Deleted flow (or another workspace's id): no row comes back.
        {
          currentFlowId: "30",
          currentNodeId: "node-1",
          currentNodeAt: reachedAt,
        },
      ],
    })

    expect(mockExecute).toHaveBeenCalledTimes(1)
    expect(result).toEqual([
      {
        flowId: "10",
        flowName: "Onboarding",
        nodeId: "node-1",
        reachedAt,
        nodeType: "sendMessage",
        nodeName: "Ask for phone",
        nodePreview: null,
      },
      null,
      {
        flowId: "20",
        flowName: "Sales",
        nodeId: "node-x",
        reachedAt,
        nodeType: null,
        nodeName: null,
        nodePreview: null,
      },
      null,
    ])
  })
})
