import { db, sql } from "@chatbotx.io/database/client"
import { type FlowNodeDisplay, resolveFlowNodeDisplay } from "./node-display"

export {
  type FlowNodeDisplay,
  isAutoGeneratedNodeName,
  resolveFlowNodeDisplay,
  truncatePreview,
} from "./node-display"

/** A contact-inbox's recorded position in a flow (see `ContactInbox.currentNodeId`). */
export type CurrentFlowNodeRef = {
  currentFlowId: string | null
  currentNodeId: string | null
  currentNodeAt: Date | null
}

export type CurrentFlowStep = FlowNodeDisplay & {
  flowId: string
  flowName: string
  nodeId: string
  reachedAt: Date
}

/**
 * Picks the most recently entered node among a contact's inboxes (a contact
 * may talk to the bot on several channels; the latest one is "current").
 */
export function pickLatestCurrentFlowNode<T extends CurrentFlowNodeRef>(
  rows: readonly T[] | null | undefined,
):
  | (T & { currentFlowId: string; currentNodeId: string; currentNodeAt: Date })
  | null {
  let latest: T | null = null
  for (const row of rows ?? []) {
    if (!(row.currentFlowId && row.currentNodeId && row.currentNodeAt)) {
      continue
    }
    if (
      !latest?.currentNodeAt ||
      new Date(row.currentNodeAt).getTime() >
        new Date(latest.currentNodeAt).getTime()
    ) {
      latest = row
    }
  }
  return latest as
    | (T & {
        currentFlowId: string
        currentNodeId: string
        currentNodeAt: Date
      })
    | null
}

export const currentFlowStepKey = (flowId: string, nodeId: string): string =>
  `${flowId}:${nodeId}`

type FlowNodeRow = {
  flowId: string | number
  flowName: string
  nodeId: string | null
  node: unknown
}

class CurrentFlowStepService {
  /**
   * Resolves display data for many recorded positions with ONE query: each
   * referenced flow joined to its published version (draft as a fallback for
   * never-published flows), unnesting only the referenced nodes so the full
   * node arrays never leave the database. Scoped to the workspace — a flow
   * id from another workspace resolves to nothing.
   *
   * Returns `null` for a ref whose flow is gone ("no active flow"); a flow
   * that still exists but no longer has the node yields `nodeType: null`.
   */
  async resolveMany(input: {
    workspaceId: string
    refs: readonly (CurrentFlowNodeRef | null | undefined)[]
  }): Promise<(CurrentFlowStep | null)[]> {
    const refs = input.refs.map((ref) =>
      ref?.currentFlowId && ref.currentNodeId && ref.currentNodeAt
        ? {
            flowId: ref.currentFlowId,
            nodeId: ref.currentNodeId,
            reachedAt: new Date(ref.currentNodeAt),
          }
        : null,
    )
    const present = refs.filter((ref) => ref !== null)
    if (present.length === 0) {
      return refs.map(() => null)
    }

    const flowIds = [...new Set(present.map((ref) => ref.flowId))]
    const nodeIds = [...new Set(present.map((ref) => ref.nodeId))]

    const result = await db.execute<FlowNodeRow>(sql`
      SELECT
        f."id" AS "flowId",
        f."name" AS "flowName",
        n.node->>'id' AS "nodeId",
        n.node AS "node"
      FROM "Flow" f
      LEFT JOIN "FlowVersion" v
        ON v."id" = COALESCE(f."currentVersionId", f."draftVersionId")
        AND v."workspaceId" = f."workspaceId"
      LEFT JOIN LATERAL (
        SELECT node
        FROM unnest(v."nodes") AS node
        WHERE node->>'id' IN (${sql.join(
          nodeIds.map((id) => sql`${id}`),
          sql`, `,
        )})
      ) n ON true
      WHERE f."workspaceId" = ${input.workspaceId}
        AND f."id" IN (${sql.join(
          flowIds.map((id) => sql`${id}::int8`),
          sql`, `,
        )})
    `)

    const flowNames = new Map<string, string>()
    const nodes = new Map<string, unknown>()
    for (const row of result.rows) {
      const flowId = String(row.flowId)
      flowNames.set(flowId, row.flowName)
      if (row.nodeId) {
        nodes.set(currentFlowStepKey(flowId, row.nodeId), row.node)
      }
    }

    return refs.map((ref) => {
      if (!ref) {
        return null
      }
      const flowName = flowNames.get(ref.flowId)
      if (flowName === undefined) {
        return null
      }
      const node = nodes.get(currentFlowStepKey(ref.flowId, ref.nodeId))
      return {
        flowId: ref.flowId,
        flowName,
        nodeId: ref.nodeId,
        reachedAt: ref.reachedAt,
        ...resolveFlowNodeDisplay(node),
      }
    })
  }

  /** Current step of a contact: its most recently entered node on any inbox. */
  async resolveForContact(input: {
    workspaceId: string
    contactId: string
  }): Promise<CurrentFlowStep | null> {
    const ref = await db.query.contactInboxModel.findFirst({
      where: {
        contactId: input.contactId,
        currentNodeAt: { isNotNull: true },
        contact: { workspaceId: input.workspaceId },
      },
      columns: {
        currentFlowId: true,
        currentNodeId: true,
        currentNodeAt: true,
      },
      orderBy: { currentNodeAt: "desc" },
    })
    return await this.resolveOne({ workspaceId: input.workspaceId, ref })
  }

  async resolveOne(input: {
    workspaceId: string
    ref: CurrentFlowNodeRef | null | undefined
  }): Promise<CurrentFlowStep | null> {
    if (!input.ref) {
      return null
    }
    const [step] = await this.resolveMany({
      workspaceId: input.workspaceId,
      refs: [input.ref],
    })
    return step ?? null
  }
}

export const currentFlowStepService = new CurrentFlowStepService()
