import { db, sql } from "@chatbotx.io/database/client"
import {
  nodeTypeSchema,
  richTextToPlainText,
  toSendTextStepVersion,
} from "@chatbotx.io/flow-config"

/** A contact-inbox's recorded position in a flow (see `ContactInbox.currentNodeId`). */
export type CurrentFlowNodeRef = {
  currentFlowId: string | null
  currentNodeId: string | null
  currentNodeAt: Date | null
}

export type FlowNodeDisplay = {
  /** Node type from the flow config, `null` when the node no longer exists. */
  nodeType: string | null
  /** The name the user gave the node in the builder, if any. */
  nodeName: string | null
  /**
   * First words of the node's first text message. Only filled when the name
   * does not identify the step on its own (missing or auto-generated like
   * "Send Message #3"), to keep the read path cheap and the UI line short.
   */
  nodePreview: string | null
}

export type CurrentFlowStep = FlowNodeDisplay & {
  flowId: string
  flowName: string
  nodeId: string
  reachedAt: Date
}

const PREVIEW_MAX_WORDS = 6
const PREVIEW_MAX_CHARS = 60

// The builder names new nodes `${typeLabel} #${n}` in the editor's locale
// (`addNewNode`); the flow-config defaults are the bare English labels.
const AUTO_NAME_SUFFIX = /\s#\d+$/
const DEFAULT_NODE_NAMES = new Set([
  "Send Message",
  "Start Flow",
  "Perform Action",
  "Condition",
  "Send Mail",
  "Split Traffic",
  "Wait",
  "Follow Up",
  "Landing Page",
  "Add Notes",
])

export function isAutoGeneratedNodeName(name: string): boolean {
  return AUTO_NAME_SUFFIX.test(name) || DEFAULT_NODE_NAMES.has(name)
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value)

export function truncatePreview(text: string): string | null {
  const words = text.replace(/\s+/g, " ").trim().split(" ").filter(Boolean)
  if (words.length === 0) {
    return null
  }
  let preview = words.slice(0, PREVIEW_MAX_WORDS).join(" ")
  let truncated = words.length > PREVIEW_MAX_WORDS
  if (preview.length > PREVIEW_MAX_CHARS) {
    preview = preview.slice(0, PREVIEW_MAX_CHARS).trimEnd()
    truncated = true
  }
  return truncated ? `${preview}…` : preview
}

function extractNodePreview(details: unknown): string | null {
  if (!(isRecord(details) && Array.isArray(details.steps))) {
    return null
  }
  for (const step of details.steps) {
    if (!isRecord(step)) {
      continue
    }
    if (step.stepType === "sendText" && typeof step.text === "string") {
      const plain = richTextToPlainText(
        step.text,
        toSendTextStepVersion(step.version),
      )
      const preview = truncatePreview(plain)
      if (preview) {
        return preview
      }
    }
    if (step.stepType === "getUserData" && typeof step.message === "string") {
      const preview = truncatePreview(step.message)
      if (preview) {
        return preview
      }
    }
  }
  return null
}

/**
 * Resolves how a flow node is shown outside the flow editor. Accepts the raw
 * jsonb node (`FlowVersion.nodes[i]`) and never throws on unexpected shapes:
 * an older or hand-edited config just yields fewer fields.
 */
export function resolveFlowNodeDisplay(node: unknown): FlowNodeDisplay {
  if (!isRecord(node)) {
    return { nodeType: null, nodeName: null, nodePreview: null }
  }
  const parsedType = nodeTypeSchema.safeParse(node.type)
  const nodeType = parsedType.success ? parsedType.data : null
  const data = isRecord(node.data) ? node.data : {}
  const rawName = typeof data.name === "string" ? data.name.trim() : ""
  const nodeName = rawName.length > 0 ? rawName : null
  const nodePreview =
    nodeName === null || isAutoGeneratedNodeName(nodeName)
      ? extractNodePreview(data.details)
      : null
  return { nodeType, nodeName, nodePreview }
}

/**
 * Picks the most recently entered node among a contact's inboxes (a contact
 * may talk to the bot on several channels; the latest one is "current").
 */
export function pickLatestCurrentFlowNode<T extends CurrentFlowNodeRef>(
  rows: readonly T[] | null | undefined,
):
  | (T & { currentFlowId: string; currentNodeId: string; currentNodeAt: Date })
  | null {
  let latest: T | null = null
  for (const row of rows ?? []) {
    if (!(row.currentFlowId && row.currentNodeId && row.currentNodeAt)) {
      continue
    }
    if (
      !latest?.currentNodeAt ||
      new Date(row.currentNodeAt).getTime() >
        new Date(latest.currentNodeAt).getTime()
    ) {
      latest = row
    }
  }
  return latest as
    | (T & {
        currentFlowId: string
        currentNodeId: string
        currentNodeAt: Date
      })
    | null
}

export const currentFlowStepKey = (flowId: string, nodeId: string): string =>
  `${flowId}:${nodeId}`

type FlowNodeRow = {
  flowId: string | number
  flowName: string
  nodeId: string | null
  node: unknown
}

class CurrentFlowStepService {
  /**
   * Resolves display data for many recorded positions with ONE query: each
   * referenced flow joined to its published version (draft as a fallback for
   * never-published flows), unnesting only the referenced nodes so the full
   * node arrays never leave the database. Scoped to the workspace — a flow
   * id from another workspace resolves to nothing.
   *
   * Returns `null` for a ref whose flow is gone ("no active flow"); a flow
   * that still exists but no longer has the node yields `nodeType: null`.
   */
  async resolveMany(input: {
    workspaceId: string
    refs: readonly (CurrentFlowNodeRef | null | undefined)[]
  }): Promise<(CurrentFlowStep | null)[]> {
    const refs = input.refs.map((ref) =>
      ref?.currentFlowId && ref.currentNodeId && ref.currentNodeAt
        ? {
            flowId: ref.currentFlowId,
            nodeId: ref.currentNodeId,
            reachedAt: new Date(ref.currentNodeAt),
          }
        : null,
    )
    const present = refs.filter((ref) => ref !== null)
    if (present.length === 0) {
      return refs.map(() => null)
    }

    const flowIds = [...new Set(present.map((ref) => ref.flowId))]
    const nodeIds = [...new Set(present.map((ref) => ref.nodeId))]

    const result = await db.execute<FlowNodeRow>(sql`
      SELECT
        f."id" AS "flowId",
        f."name" AS "flowName",
        n.node->>'id' AS "nodeId",
        n.node AS "node"
      FROM "Flow" f
      LEFT JOIN "FlowVersion" v
        ON v."id" = COALESCE(f."currentVersionId", f."draftVersionId")
        AND v."workspaceId" = f."workspaceId"
      LEFT JOIN LATERAL (
        SELECT node
        FROM unnest(v."nodes") AS node
        WHERE node->>'id' IN (${sql.join(
          nodeIds.map((id) => sql`${id}`),
          sql`, `,
        )})
      ) n ON true
      WHERE f."workspaceId" = ${input.workspaceId}
        AND f."id" IN (${sql.join(
          flowIds.map((id) => sql`${id}::int8`),
          sql`, `,
        )})
    `)

    const flowNames = new Map<string, string>()
    const nodes = new Map<string, unknown>()
    for (const row of result.rows) {
      const flowId = String(row.flowId)
      flowNames.set(flowId, row.flowName)
      if (row.nodeId) {
        nodes.set(currentFlowStepKey(flowId, row.nodeId), row.node)
      }
    }

    return refs.map((ref) => {
      if (!ref) {
        return null
      }
      const flowName = flowNames.get(ref.flowId)
      if (flowName === undefined) {
        return null
      }
      const node = nodes.get(currentFlowStepKey(ref.flowId, ref.nodeId))
      return {
        flowId: ref.flowId,
        flowName,
        nodeId: ref.nodeId,
        reachedAt: ref.reachedAt,
        ...resolveFlowNodeDisplay(node),
      }
    })
  }

  /** Current step of a contact: its most recently entered node on any inbox. */
  async resolveForContact(input: {
    workspaceId: string
    contactId: string
  }): Promise<CurrentFlowStep | null> {
    const ref = await db.query.contactInboxModel.findFirst({
      where: {
        contactId: input.contactId,
        currentNodeAt: { isNotNull: true },
        contact: { workspaceId: input.workspaceId },
      },
      columns: {
        currentFlowId: true,
        currentNodeId: true,
        currentNodeAt: true,
      },
      orderBy: { currentNodeAt: "desc" },
    })
    return await this.resolveOne({ workspaceId: input.workspaceId, ref })
  }

  async resolveOne(input: {
    workspaceId: string
    ref: CurrentFlowNodeRef | null | undefined
  }): Promise<CurrentFlowStep | null> {
    if (!input.ref) {
      return null
    }
    const [step] = await this.resolveMany({
      workspaceId: input.workspaceId,
      refs: [input.ref],
    })
    return step ?? null
  }
}

export const currentFlowStepService = new CurrentFlowStepService()
