import {
  nodeTypeSchema,
  richTextToPlainText,
  toSendTextStepVersion,
} from "@chatbotx.io/flow-config"

// Pure (no database) so the builder's client components can label flow nodes
// the same way the server does — exported as `@chatbotx.io/business/flow-node-display`.

export type FlowNodeDisplay = {
  /** Node type from the flow config, `null` when the node no longer exists. */
  nodeType: string | null
  /** The name the user gave the node in the builder, if any. */
  nodeName: string | null
  /**
   * First words of the node's first text message. Only filled when the name
   * does not identify the step on its own (missing or auto-generated like
   * "Send Message #3"), to keep the read path cheap and the UI line short.
   */
  nodePreview: string | null
}

const PREVIEW_MAX_WORDS = 6
const PREVIEW_MAX_CHARS = 60

// The builder names new nodes `${typeLabel} #${n}` in the editor's locale
// (`addNewNode`); the flow-config defaults are the bare English labels.
const AUTO_NAME_SUFFIX = /\s#\d+$/
const DEFAULT_NODE_NAMES = new Set([
  "Send Message",
  "Start Flow",
  "Perform Action",
  "Condition",
  "Send Mail",
  "Split Traffic",
  "Wait",
  "Follow Up",
  "Landing Page",
  "Add Notes",
])

export function isAutoGeneratedNodeName(name: string): boolean {
  return AUTO_NAME_SUFFIX.test(name) || DEFAULT_NODE_NAMES.has(name)
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value)

export function truncatePreview(text: string): string | null {
  const words = text.replace(/\s+/g, " ").trim().split(" ").filter(Boolean)
  if (words.length === 0) {
    return null
  }
  let preview = words.slice(0, PREVIEW_MAX_WORDS).join(" ")
  let truncated = words.length > PREVIEW_MAX_WORDS
  if (preview.length > PREVIEW_MAX_CHARS) {
    preview = preview.slice(0, PREVIEW_MAX_CHARS).trimEnd()
    truncated = true
  }
  return truncated ? `${preview}…` : preview
}

function extractNodePreview(details: unknown): string | null {
  if (!(isRecord(details) && Array.isArray(details.steps))) {
    return null
  }
  for (const step of details.steps) {
    if (!isRecord(step)) {
      continue
    }
    if (step.stepType === "sendText" && typeof step.text === "string") {
      const plain = richTextToPlainText(
        step.text,
        toSendTextStepVersion(step.version),
      )
      const preview = truncatePreview(plain)
      if (preview) {
        return preview
      }
    }
    if (step.stepType === "getUserData" && typeof step.message === "string") {
      const preview = truncatePreview(step.message)
      if (preview) {
        return preview
      }
    }
  }
  return null
}

/**
 * Resolves how a flow node is shown outside the flow editor. Accepts the raw
 * jsonb node (`FlowVersion.nodes[i]`) and never throws on unexpected shapes:
 * an older or hand-edited config just yields fewer fields.
 */
export function resolveFlowNodeDisplay(node: unknown): FlowNodeDisplay {
  if (!isRecord(node)) {
    return { nodeType: null, nodeName: null, nodePreview: null }
  }
  const parsedType = nodeTypeSchema.safeParse(node.type)
  const nodeType = parsedType.success ? parsedType.data : null
  const data = isRecord(node.data) ? node.data : {}
  const rawName = typeof data.name === "string" ? data.name.trim() : ""
  const nodeName = rawName.length > 0 ? rawName : null
  const nodePreview =
    nodeName === null || isAutoGeneratedNodeName(nodeName)
      ? extractNodePreview(data.details)
      : null
  return { nodeType, nodeName, nodePreview }
}
